### ISSUE TITLE
don't use ezbids container

### ISSUE THREAD

**Issue by soichih** [brainlife/app-stage#1]
This app uses ezbids container to run dcm2niix (for XNAT) but ezbids container is huge (>6G) and we just need dcm2niix. We should stop using this container.

I am submitting this because right now our io server is hosed because there are some process that are stuck with a bunch of singularity trying to cache this container (maybe the container got updated?) and the whole machine is IO starved

**Comment by francopestilli** [comment]
it sounds like this is a priority!

**Comment by soichih** [comment]
I've updated this service to use a dedicated container `brainlife/stage` that is much smaller (Thanks @dlevitas for the Dockerfile).
